---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/pcavar/pcavar.html
    type: html
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/87737/articles/276899/master/file/figures/pcavar/pcavar.html"
    folder_url: "/users/87737/articles/276899/master/folder/figures/pcavar"
