---
version: 2
multicolumn: true
web-width: 800
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/corrmat/corrmat.html
    type: html
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/87737/articles/276899/master/file/figures/corrmat/corrmat.html"
    folder_url: "/users/87737/articles/276899/master/folder/figures/corrmat"
