---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/KualitasAir_ArifS - Sheet1/KualitasAir_ArifS - Sheet1.csv
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/87737/articles/200842/master/file/figures/KualitasAir_ArifS%20-%20Sheet1/KualitasAir_ArifS%20-%20Sheet1.csv"
    folder_url: "/users/87737/articles/200842/master/folder/figures/KualitasAir_ArifS
      - Sheet1"
    treatFirstLineAsHeader: true
