---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/elevation/grid1.svg
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/87737/articles/276899/master/folder/figures/elevation"
    url: "/users/87737/articles/276899/master/file/figures/elevation/grid1.svg"
